// frontend/src/modules/embed/components/EmbedSessionHistoryPanel.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { ChatDotRound, Clock, Delete, Plus, Search } from "@element-plus/icons-vue";

import type { SessionSummary } from "@/modules/embed/composables/useEmbeddedAssistant";

const props = defineProps<{
  currentSessionId: string | null;
  sessions: SessionSummary[];
  loading: boolean;
  error: string | null;
  deletingSessionId: string | null;
}>();

const emit = defineEmits<{
  select: [sessionId: string];
  create: [];
  delete: [sessionId: string];
  load: [];
  refresh: [];
}>();

const visible = ref(false);
const keyword = ref("");

const filteredSessions = computed(() => {
  const normalizedKeyword = keyword.value.trim().toLowerCase();
  if (!normalizedKeyword) {
    return props.sessions;
  }

  return props.sessions.filter((session) => {
    return (
      session.title.toLowerCase().includes(normalizedKeyword) ||
      (session.preview ?? "").toLowerCase().includes(normalizedKeyword)
    );
  });
});

watch(visible, (value) => {
  if (value) {
    emit("load");
  } else {
    keyword.value = "";
  }
});

function handleSelect(sessionId: string) {
  emit("select", sessionId);
  visible.value = false;
}

function handleCreate() {
  emit("create");
  visible.value = false;
}

function formatSessionTime(value: string) {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) {
    return "";
  }

  const now = new Date();
  const diffMs = now.getTime() - date.getTime();
  if (diffMs >= 0 && diffMs < 60 * 1000) {
    return "刚刚";
  }
  if (diffMs >= 0 && diffMs < 60 * 60 * 1000) {
    return `${Math.max(1, Math.floor(diffMs / 60000))} 分钟前`;
  }

  return new Intl.DateTimeFormat("zh-CN", {
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
  }).format(date);
}
</script>

<template>
  <el-popover
    v-model:visible="visible"
    trigger="click"
    placement="bottom-end"
    :width="360"
    :z-index="2147483001"
    popper-class="embed-history-popover"
  >
    <template #reference>
      <button
        type="button"
        class="embed-history-panel__trigger"
        title="历史对话"
        aria-label="历史对话"
      >
        <el-icon><Clock /></el-icon>
      </button>
    </template>

    <section class="embed-history-panel">
      <header class="embed-history-panel__header">
        <div class="embed-history-panel__header-main">
          <div class="embed-history-panel__icon">
            <el-icon><Clock /></el-icon>
          </div>
          <div class="embed-history-panel__title-wrap">
            <strong class="embed-history-panel__title">历史对话</strong>
            <span v-if="sessions.length > 0" class="embed-history-panel__count">{{ sessions.length }}</span>
          </div>
        </div>
      </header>

      <label class="embed-history-panel__search">
        <el-icon><Search /></el-icon>
        <input v-model="keyword" type="text" placeholder="搜索历史对话..." />
      </label>

      <div class="embed-history-panel__body">
        <div v-if="error" class="embed-history-panel__error">
          {{ error }}
        </div>

        <div v-if="loading" class="embed-history-panel__empty">
          <el-icon class="is-loading"><Clock /></el-icon>
          <span>正在加载历史对话...</span>
        </div>

        <div v-else-if="filteredSessions.length === 0" class="embed-history-panel__empty">
          <el-icon><ChatDotRound /></el-icon>
          <span>{{ sessions.length === 0 ? "暂无历史对话" : "没有匹配的会话" }}</span>
        </div>

        <div v-else class="embed-history-panel__list">
          <div
            v-for="session in filteredSessions"
            :key="session.id"
            class="embed-history-panel__item"
            :class="{ 'is-active': currentSessionId === session.id }"
          >
            <button
              type="button"
              class="embed-history-panel__item-main-button"
              @click="handleSelect(session.id)"
            >
            <div class="embed-history-panel__item-icon">
              <el-icon><ChatDotRound /></el-icon>
            </div>
            <div class="embed-history-panel__item-main">
              <div class="embed-history-panel__item-title">{{ session.title }}</div>
              <div v-if="session.preview" class="embed-history-panel__item-preview">
                {{ session.preview }}
              </div>
              <div class="embed-history-panel__item-time">{{ formatSessionTime(session.createdAt) }}</div>
            </div>
            </button>
            <button
              type="button"
              class="embed-history-panel__delete"
              :disabled="deletingSessionId === session.id"
              title="删除会话"
              @click.stop="emit('delete', session.id)"
            >
              <el-icon v-if="deletingSessionId === session.id" class="is-loading"><Clock /></el-icon>
              <el-icon v-else><Delete /></el-icon>
            </button>
          </div>
        </div>
      </div>

      <footer class="embed-history-panel__footer">
        <button type="button" class="embed-history-panel__create" @click="handleCreate">
          <el-icon><Plus /></el-icon>
          <span>新建对话</span>
        </button>
      </footer>
    </section>
  </el-popover>
</template>

<style scoped>
.embed-history-panel {
  display: flex;
  flex-direction: column;
  max-height: min(70vh, 560px);
}

.embed-history-panel__header {
  padding-bottom: 12px;
}

.embed-history-panel__header-main {
  display: flex;
  align-items: center;
  gap: 10px;
}

.embed-history-panel__icon {
  display: inline-flex;
  width: 30px;
  height: 30px;
  align-items: center;
  justify-content: center;
  border-radius: 12px;
  background: linear-gradient(135deg, #2563eb 0%, #4f46e5 100%);
  color: #ffffff;
}

.embed-history-panel__title-wrap {
  display: flex;
  align-items: center;
  gap: 8px;
}

.embed-history-panel__title {
  font-size: 14px;
  color: #0f172a;
}

.embed-history-panel__count {
  padding: 2px 8px;
  border-radius: 999px;
  background: #f1f5f9;
  font-size: 11px;
  color: #64748b;
}

.embed-history-panel__search {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 12px;
  padding: 0 12px;
  height: 40px;
  border: 1px solid #e2e8f0;
  border-radius: 14px;
  background: #f8fafc;
  color: #94a3b8;
}

.embed-history-panel__search input {
  flex: 1;
  min-width: 0;
  border: 0;
  outline: none;
  background: transparent;
  font-size: 13px;
  color: #334155;
}

.embed-history-panel__body {
  min-height: 180px;
  max-height: 360px;
  overflow-y: auto;
}

.embed-history-panel__error {
  margin-bottom: 10px;
  padding: 10px 12px;
  border: 1px solid #fecaca;
  border-radius: 12px;
  background: #fef2f2;
  font-size: 12px;
  color: #dc2626;
}

.embed-history-panel__empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 8px;
  min-height: 180px;
  color: #94a3b8;
  font-size: 12px;
}

.embed-history-panel__list {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.embed-history-panel__item {
  display: flex;
  width: 100%;
  align-items: flex-start;
  gap: 10px;
  padding: 10px 12px;
  border: 1px solid transparent;
  border-radius: 14px;
  background: transparent;
  transition: all 0.2s ease;
}

.embed-history-panel__item:hover {
  border-color: #e2e8f0;
  background: #f8fafc;
}

.embed-history-panel__item.is-active {
  border-color: #bfdbfe;
  background: #eff6ff;
}

.embed-history-panel__item-main-button {
  display: flex;
  flex: 1;
  min-width: 0;
  align-items: flex-start;
  gap: 10px;
  padding: 0;
  border: 0;
  background: transparent;
  text-align: left;
  cursor: pointer;
}

.embed-history-panel__item-icon {
  display: inline-flex;
  width: 28px;
  height: 28px;
  align-items: center;
  justify-content: center;
  border-radius: 10px;
  background: #e2e8f0;
  color: #475569;
  flex-shrink: 0;
}

.embed-history-panel__item.is-active .embed-history-panel__item-icon {
  background: #dbeafe;
  color: #2563eb;
}

.embed-history-panel__item-main {
  flex: 1;
  min-width: 0;
}

.embed-history-panel__item-title {
  font-size: 13px;
  font-weight: 600;
  line-height: 1.5;
  color: #334155;
}

.embed-history-panel__item-preview {
  margin-top: 2px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  font-size: 11px;
  color: #94a3b8;
}

.embed-history-panel__item-time {
  margin-top: 6px;
  font-size: 10px;
  color: #94a3b8;
}

.embed-history-panel__delete {
  display: inline-flex;
  width: 28px;
  height: 28px;
  align-items: center;
  justify-content: center;
  border: 0;
  border-radius: 10px;
  background: transparent;
  color: #cbd5e1;
  cursor: pointer;
  transition: all 0.2s ease;
  flex-shrink: 0;
}

.embed-history-panel__delete:hover:not(:disabled) {
  background: #fef2f2;
  color: #ef4444;
}

.embed-history-panel__delete:disabled {
  cursor: not-allowed;
  opacity: 0.5;
}

.embed-history-panel__footer {
  padding-top: 12px;
  border-top: 1px solid #f1f5f9;
  margin-top: 12px;
}

.embed-history-panel__create {
  display: flex;
  width: 100%;
  align-items: center;
  justify-content: center;
  gap: 8px;
  height: 42px;
  border: 1px dashed #93c5fd;
  border-radius: 14px;
  background: rgba(239, 246, 255, 0.7);
  color: #2563eb;
  font-size: 13px;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.2s ease;
}

.embed-history-panel__create:hover {
  background: rgba(219, 234, 254, 0.85);
  border-color: #60a5fa;
}

.embed-history-panel__trigger {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 34px;
  height: 34px;
  border: 1px solid #e2e8f0;
  border-radius: 10px;
  background: #ffffff;
  color: #475569;
  cursor: pointer;
  transition: all 0.2s ease;
  box-shadow: 0 2px 10px rgba(15, 23, 42, 0.04);
}

.embed-history-panel__trigger:hover {
  background: #f8fafc;
  border-color: #cbd5e1;
  color: #0f172a;
}
</style>

// frontend/features/embed/components/EmbedSessionHistoryPanel.tsx
"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { useSearchParams } from "next/navigation";
import {
  Bot,
  Clock,
  Loader2,
  MessageSquare,
  Plus,
  Search,
  Trash2,
  X,
} from "lucide-react";
import { AnimatePresence, motion } from "framer-motion";

import { Button } from "@/components/ui/button";
import type { AskSessionSummary } from "@/lib/api/endpoints/ask";
import { embedApi } from "@/lib/api/endpoints/embed";
import { cn } from "@/lib/utils";
import type { Session } from "../hooks/useEmbeddedAssistant";

const SESSION_LIST_LIMIT = 30;

interface EmbedSessionHistoryPanelProps {
  currentSessionId: string | null;
  onSelectSession: (sessionId: string) => void;
  onNewSession: () => void;
}

function toSession(item: AskSessionSummary): Session {
  return {
    id: item.session_id,
    title: item.title || "新对话",
    createdAt: item.updated_at || item.created_at,
    preview: item.preview ?? null,
  };
}

function formatPanelError(error: unknown, fallback: string): string {
  return error instanceof Error && error.message ? error.message : fallback;
}

function formatSessionTime(value: string): string {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "";

  const now = new Date();
  const diffMs = now.getTime() - date.getTime();
  if (diffMs >= 0 && diffMs < 60 * 1000) return "刚刚";
  if (diffMs >= 0 && diffMs < 60 * 60 * 1000) {
    return `${Math.max(1, Math.floor(diffMs / 60000))} 分钟前`;
  }

  return new Intl.DateTimeFormat("zh-CN", {
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
  }).format(date);
}

export function EmbedSessionHistoryPanel({
  currentSessionId,
  onSelectSession,
  onNewSession,
}: EmbedSessionHistoryPanelProps) {
  const searchParams = useSearchParams();
  const token = searchParams.get("token")?.trim() || "";

  const [isOpen, setIsOpen] = useState(false);
  const [historyKeyword, setHistoryKeyword] = useState("");
  const [sessions, setSessions] = useState<Session[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [deletingSessionId, setDeletingSessionId] = useState<string | null>(null);

  const filteredSessions = useMemo(() => {
    const keyword = historyKeyword.trim().toLowerCase();
    if (!keyword) return sessions;
    return sessions.filter(
      (session) =>
        session.title.toLowerCase().includes(keyword) ||
        (session.preview ?? "").toLowerCase().includes(keyword),
    );
  }, [historyKeyword, sessions]);

  const loadSessions = useCallback(async () => {
    if (!token) return;

    setIsLoading(true);
    setError(null);
    try {
      const response = await embedApi.listSessions(token, SESSION_LIST_LIMIT);
      setSessions(response.map(toSession));
    } catch (err) {
      setError(formatPanelError(err, "加载历史会话失败"));
    } finally {
      setIsLoading(false);
    }
  }, [token]);

  useEffect(() => {
    if (!isOpen) return;
    void loadSessions();
  }, [isOpen, loadSessions]);

  const handleSelect = (sessionId: string) => {
    onSelectSession(sessionId);
    setIsOpen(false);
  };

  const handleDelete = async (sessionId: string) => {
    if (!sessionId || !token || deletingSessionId) return;

    setDeletingSessionId(sessionId);
    setError(null);
    try {
      await embedApi.deleteSession(token, sessionId);
      setSessions((current) => current.filter((session) => session.id !== sessionId));
      if (currentSessionId === sessionId) {
        onNewSession();
      }
    } catch (err) {
      setError(formatPanelError(err, "删除会话失败"));
    } finally {
      setDeletingSessionId(null);
    }
  };

  const overlay = (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-[9999]">
            {/* Backdrop — animated, blurred */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.18 }}
              className="absolute inset-0 bg-slate-900/20 backdrop-blur-[2px]"
              onClick={() => setIsOpen(false)}
            />

            {/* Panel — spring slide-in from right */}
            <motion.aside
              initial={{ x: "100%", opacity: 0.6 }}
              animate={{ x: 0, opacity: 1 }}
              exit={{ x: "100%", opacity: 0 }}
              transition={{ type: "spring", stiffness: 320, damping: 32 }}
              style={{
                width: "clamp(280px, 44vw, 400px)",
                maxWidth: "calc(100vw - 12px)",
              }}
              className="absolute bottom-2 right-2 top-2 flex flex-col overflow-hidden rounded-2xl border border-slate-200/80 bg-white shadow-2xl shadow-slate-300/40"
            >
              {/* 4. Panel header */}
              <div className="shrink-0 border-b border-slate-100 bg-white px-4 pb-3 pt-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <div className="flex h-7 w-7 items-center justify-center rounded-xl bg-gradient-to-br from-blue-500 to-indigo-600 shadow shadow-blue-200">
                      <Clock className="h-3.5 w-3.5 text-white" />
                    </div>
                    <span className="text-[14px] font-semibold text-slate-800">历史会话</span>
                    {sessions.length > 0 && (
                      <span className="rounded-full bg-slate-100 px-1.5 py-0.5 text-[11px] font-medium text-slate-500">
                        {sessions.length}
                      </span>
                    )}
                  </div>
                  <Button
                    variant="ghost"
                    size="icon"
                    onClick={() => setIsOpen(false)}
                    className="h-7 w-7 rounded-full text-slate-400 hover:bg-slate-100 hover:text-slate-600"
                    title="关闭历史会话"
                  >
                    <X className="h-3.5 w-3.5" />
                  </Button>
                </div>

                {/* Search */}
                <div className="relative mt-3">
                  <Search className="absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-slate-400" />
                  <input
                    type="text"
                    value={historyKeyword}
                    onChange={(event) => setHistoryKeyword(event.target.value)}
                    placeholder="搜索历史会话..."
                    className="w-full rounded-xl border border-slate-200 bg-slate-50 py-2 pl-8 pr-4 text-[13px] outline-none transition-all focus:border-blue-400 focus:bg-white focus:ring-2 focus:ring-blue-500/15"
                  />
                </div>
              </div>

              {/* Session list */}
              <div className="min-h-0 flex-1 overflow-y-auto px-3 py-3">
                <AnimatePresence>
                  {error ? (
                    <motion.div
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      className="mb-2 rounded-xl border border-red-100 bg-red-50 px-3 py-2 text-[12px] text-red-600"
                    >
                      {error}
                    </motion.div>
                  ) : null}
                </AnimatePresence>

                {isLoading ? (
                  <div className="flex flex-col items-center justify-center py-16 text-slate-400">
                    <Loader2 className="mb-3 h-6 w-6 animate-spin text-blue-500" />
                    <p className="text-[12px]">加载中...</p>
                  </div>
                ) : filteredSessions.length === 0 ? (
                  /* 6. Empty state */
                  <div className="flex flex-col items-center justify-center py-16 text-slate-400">
                    <div className="mb-3 flex h-12 w-12 items-center justify-center rounded-2xl bg-slate-100">
                      <MessageSquare className="h-6 w-6 opacity-40" />
                    </div>
                    <p className="text-[13px] font-medium text-slate-500">
                      {sessions.length === 0 ? "暂无历史对话" : "没有匹配的会话"}
                    </p>
                    <p className="mt-1 text-[11px] text-slate-400">
                      {sessions.length === 0 ? "开始第一次对话吧" : "换个关键词试试"}
                    </p>
                  </div>
                ) : (
                  /* 5. Session items */
                  <div className="space-y-1.5">
                    <AnimatePresence initial={false}>
                      {filteredSessions.map((session, index) => (
                        <motion.div
                          key={session.id}
                          initial={{ opacity: 0, x: 12 }}
                          animate={{ opacity: 1, x: 0 }}
                          exit={{ opacity: 0, x: -8, height: 0 }}
                          transition={{ delay: index * 0.03, duration: 0.2 }}
                          className={cn(
                            "group relative flex items-start gap-2 rounded-xl border px-3 py-2.5 transition-all",
                            currentSessionId === session.id
                              ? "border-blue-200 bg-blue-50"
                              : "border-transparent bg-transparent hover:border-slate-200 hover:bg-slate-50",
                          )}
                        >
                          <button
                            type="button"
                            onClick={() => handleSelect(session.id)}
                            className="flex min-w-0 flex-1 items-start gap-2.5 text-left"
                          >
                            <div
                              className={cn(
                                "mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-lg transition-colors",
                                currentSessionId === session.id
                                  ? "bg-blue-100 text-blue-600"
                                  : "bg-slate-100 text-slate-500 group-hover:bg-blue-100 group-hover:text-blue-600",
                              )}
                            >
                              <Bot className="h-3.5 w-3.5" />
                            </div>
                            <div className="min-w-0 flex-1">
                              <div
                                className={cn(
                                  "truncate text-[13px] font-medium leading-5",
                                  currentSessionId === session.id
                                    ? "text-blue-700"
                                    : "text-slate-700",
                                )}
                              >
                                {session.title}
                              </div>
                              {session.preview && (
                                <div className="mt-0.5 truncate text-[11px] leading-4 text-slate-400">
                                  {session.preview}
                                </div>
                              )}
                              <div className="mt-1 text-[10px] text-slate-400">
                                {formatSessionTime(session.createdAt)}
                              </div>
                            </div>
                          </button>

                          {/* Delete button — Trash2 icon */}
                          <Button
                            variant="ghost"
                            size="icon"
                            disabled={deletingSessionId === session.id}
                            onClick={() => void handleDelete(session.id)}
                            title="删除会话"
                            className="h-6 w-6 shrink-0 self-center rounded-lg text-slate-300 opacity-0 hover:bg-red-50 hover:text-red-500 group-hover:opacity-100 disabled:opacity-40"
                          >
                            {deletingSessionId === session.id ? (
                              <Loader2 className="h-3 w-3 animate-spin" />
                            ) : (
                              <Trash2 className="h-3 w-3" />
                            )}
                          </Button>
                        </motion.div>
                      ))}
                    </AnimatePresence>
                  </div>
                )}
              </div>

              {/* 7. Footer — dashed new session button */}
              <div className="shrink-0 border-t border-slate-100 px-3 py-3">
                <button
                  type="button"
                  onClick={() => {
                    onNewSession();
                    setIsOpen(false);
                  }}
                  className="flex w-full items-center justify-center gap-2 rounded-xl border border-dashed border-blue-300 bg-blue-50/50 py-2.5 text-[13px] font-medium text-blue-600 transition-all hover:border-blue-400 hover:bg-blue-100/60 hover:shadow-sm active:scale-[0.99]"
                >
                  <Plus className="h-4 w-4" />
                  新建会话
                </button>
              </div>
            </motion.aside>
          </div>
        )}
      </AnimatePresence>
  );

  return (
    <>
      <Button
        variant="ghost"
        size="icon"
        onClick={() => setIsOpen(true)}
        className="h-8 w-8 rounded-full text-slate-400 hover:bg-slate-100 hover:text-slate-600"
        title="历史会话"
      >
        <Clock className="h-4 w-4" />
      </Button>
      {typeof document !== "undefined" ? createPortal(overlay, document.body) : null}
    </>
  );
}
